import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { IconBtn } from "../../base/icon-btn.slint";
import { Divider } from "../../base/divider.slint";
import { Encode } from "./encode.slint";
import { Decode } from "./decode.slint";

export component Bodyer inherits Rectangle {
    VerticalLayout {
        padding: Theme.spacing * 10;

        if Store.panel-type == "encode": Encode {
            width: 100%;
            height: parent.height - parent.padding * 2;
        }

        if Store.panel-type == "decode": Decode {
            width: 100%;
            height: parent.height - parent.padding * 2;
        }
    }
}

