import { Theme } from "../theme.slint";
import { Logic } from "../logic.slint";
import { Store } from "../store.slint";
import { Header } from "./header.slint";
import { Bodyer } from "./bodyer/panel.slint";
import { Divider } from "../base/divider.slint";

export component Panel inherits VerticalLayout {
    padding: Theme.padding;
    spacing: Theme.spacing;

    header := Header {}
    bodyer := Bodyer {
        height: parent.height - header.height - parent.spacing - parent.padding * 2;
    }
}

