import { SettingDialogConfig, Store } from "./store.slint";

export struct Position {
    x: length,
    y: length,
}

export global Logic {
    callback hide-window();
    callback show-window();
    callback window-position() -> Position;
    callback update-position(int, int); // argument: position-x, position-y

    callback show-message(string, string); // argument: message, type
    callback copy-to-clipboard(string);
    callback handle-ok-cancel-dialog(string, string);

    callback clean-cache();

    callback setting-cancel();
    callback setting-ok(SettingDialogConfig);

    callback encode(string); // argument: password
    callback decode(string); // argument: password
    callback cancel-encode();
    callback cancel-decode();

    callback load-encode-src-file();
    callback load-encode-append-file();
    callback load-encode-dst-file();

    callback load-decode-src-file();
    callback load-decode-dst-file();

    callback handle-password-dialog(string, string, string); // argument: type, uuid, password

}

