import { Translator, Translation} from "./translator.slint";
import { MDItem } from "./base/data.slint";

export struct EncodeSpec {
    src-file: string,
    append-file: string,
    dst-file: string,
    progress: float,
}

export struct DecodeSpec {
    src-file: string,
    dst-file: string,
    progress: float,
}

export struct Password {
    show: bool,
    handle-type: string,
    handle-uuid: string,
}

export struct MessageItem {
    text: string,
    text-type: string,
}

export struct OkCancelDialogSetting {
    title-type: string,
    title-text: string,
    body-text: string,
    handle-type: string,
    handle-uuid: string,
}

export struct SettingUI {
    font-size: string,
    font-family: string,
    win-width: string,
    win-height: string,
    language: string,
}

export struct SettingDialogConfig {
    show: bool,
    ui: SettingUI,
}

export struct AboutDialog {
    show: bool,
    title: string,
    text: string,
    sponsor: string,
}

export global Store  {
    in-out property<string> panel-type: "encode";

    in-out property<EncodeSpec> encode-spec;
    // {
    //     src-file: "/home/blue/如何为歌曲配和弦.png",
    //     append-file: "/home/blue/如何为歌曲配和弦.png",
    //     dst-file: "/home/blue/如何为歌曲配和弦.png",
    // };

    in-out property<DecodeSpec> decode-spec;

    in-out property<MessageItem> message;
    in-out property<Password> password-dialog-config: { show: false };
    in-out property<OkCancelDialogSetting> ok-cancel-dialog-setting;

    in-out property<SettingDialogConfig> setting-dialog-config: {
        show: false,
        ui: {
            font-size: "18",
            font-family: "SourceHanSerifCN",
            win-width: "600",
            win-height: "400",
            language: "cn",
        }
    };

    in-out property<AboutDialog> about-dialog: {
        show: false,
        title: "HideBox v0.0.1",
        text: "Based on Slint-UI. Copyright 2022-2030 The Heng30 Company Ltd. All rights reserved. The program is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.",
        sponsor: "0xf1199999751b1a3A74590adBf95401D19AB30014",
    };

    in-out property<Translation> translator: Translator.translation(setting-dialog-config.ui.language == "cn");

    in-out property<{show: bool, text-cn: string, text-en: string}> help-dialog: {
        show: false,
        text-cn:
              "配置和数据:\n"
            + "  1. 配置保存在~/.config/hidebox目录下。\n"
            + "  2. 数据保存在~/.local/share/hidebox目录下。\n"
            + "\n注意事项:\n"
            + "  1. 需要安装本地文件框：kdialog/zenity。\n",

        text-en:
              "Configuration and data:\n"
            + "  1. Configuration is stored in the ~/.config/hidebox directory.\n"
            + "  2. Data is stored in the ~/.local/share/hidebox directory.\n"
            + "\nNote:\n"
            + "  1. Need to install file dialog: kdialog/zenity.\n",
    };
}
